function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}
function usePrompt(text){document.getElementById('prompt').value=text;scrollToId('assistant');setTimeout(()=>document.getElementById('prompt').focus(),400)}
function addMessage(text,cls){const box=document.getElementById('messages'),el=document.createElement('div');el.className='message '+cls;el.textContent=text;box.appendChild(el);box.scrollTop=box.scrollHeight}
function askAI(){const input=document.getElementById('prompt'),text=input.value.trim();if(!text)return;addMessage(text,'user');input.value='';setTimeout(()=>{let r='I’m NEXA AI. This demo is ready for a real AI backend. Connect your server-side AI API and I can answer this request.';if(/hello|hi/i.test(text))r='Hello! I’m NEXA AI. How can I help you today?';if(/business|idea/i.test(text))r='A strong business idea starts with a real problem, a clear customer and a simple way to deliver value.';if(/ai|artificial intelligence/i.test(text))r='Artificial intelligence is software that can recognize patterns, generate content and perform tasks that normally require human reasoning.';if(/email|write/i.test(text))r='Sure. Tell me who the email is for, the purpose and the tone you want.';addMessage(r,'ai')},500)}
function openAuth(mode){document.getElementById('authModal').classList.remove('hidden');const login=mode==='login';document.getElementById('authTitle').textContent=login?'Welcome back':'Create your account';document.getElementById('authSubtitle').textContent=login?'Log in to continue with NEXA AI.':'Start using NEXA AI today.';document.getElementById('authSwitch').innerHTML=login?'New to NEXA AI? <button onclick="openAuth(\'signup\')">Create account</button>':'Already have an account? <button onclick="openAuth(\'login\')">Log in</button>'}
function closeAuth(){document.getElementById('authModal').classList.add('hidden')}
function googleAuth(){alert('Google Sign-In UI is ready. To make it real, connect Firebase or Supabase OAuth credentials.')}
function emailAuth(){const e=document.getElementById('authEmail').value.trim();if(!e){alert('Please enter your email.');return}alert('Demo account form submitted. Real authentication needs a backend/auth provider.')}
function startCheckout(plan){alert('Checkout for NEXA AI Plus '+(plan==='weekly'?'€5/week':'€20/month')+' is ready in the UI. Connect Stripe and a backend to process real payments.')}
